### PR TITLE
Restart Button plus + Small menu updates

### PR DESCRIPTION
**Pull request by TheCodingCrafter**
Added a Restart Button to the main menu, would have been in options menu but I ran into some issues with setting saving when restarting.

Menu was Also updated to have a title and look slightly nicer, I moved the "Open Song Folder" button to a small text at the bottom left of the screen to reduce the space taken up by the buttons.

Notes:
- "restart.pyw" is redundant right now, but I did it this way to make it easier to expand on in the future.
- Color of Title is randomly selected from a list, but will sometimes clash with the selected theme much as the text in options menu does when you have a bright theme selected.
- I did not remove the code for the "Open Song Folder" button entirely, instead commenting it out.

### CODE REVIEW

**Comment by quasar098** [comment]
i will take a look at this soon

**Comment by quasar098** [comment]
i do not like how it uses the system function

**Comment by quasar098** [comment]
can you revert your commit and fix the diff on configpage.py because i think you overwrite the lf with crlf or vice versa which cause a huge diff which i am too lazy to check

**Comment by TheCodingCrafter** [comment]
alr ill look at it

**Comment by TheCodingCrafter** [comment]
ok so I looked at it and I don't think I even changed anything in configpage.py, so you can probably just not keep that portion of it, also I might be able change the restart function to be Linux compatible but I will need to look into it to see how as I do not have a Linux machine.

**Comment by quasar098** [comment]
use wsl2, i am extremely busy currently but will try to get to this before the 14th

**Comment by quasar098** [comment]
tbh i dont think i will accept this pr because the way you have the restarting working is kinda jank and looks sort of duct taped together weirdly and wont work for obscure operating systems, and i will probably get a lot of youtube comments saying that the restart button is not working, so i will not accept this pr for now

the title screen is good, but i dont think restart will be used more often than open songs folder because adding custom songs is something that a lot of people want to do and do often, but restarting is only for doing shaders which is kinda niche and only a few people will do it, so the more common user features should probably take up more screen space. also the open song folder text in the bottom left looks very out of place so probably move it back i think

i was also thinking that for the title, the words could be closer together and also change color when you click on it sort of like the animation when you click on the square in the title screen where it squishes, but also the title would rotate a little. that's all

**Comment by TheCodingCrafter** [comment]
alright thats cool, ill look at changing the menu

**Comment by quasar098** [comment]
whoops accidentally closed it

**Comment by quasar098** [comment]
closing due to inactivity

**Pull request closed without merging**
