### PR TITLE
Update square.py 2

### PR DESCRIPTION
**Pull request by Gininabtl**
i changed the code - how do i download it now?

### CODE REVIEW

**Comment by quasar098** [comment]
download zip button
image

**Comment by Gininabtl** [comment]
but that file is still with the old code on the square py

**Comment by Gininabtl** [comment]
look dont mean to bother you, promise you will get more downloads more answering these questions, i have no idea in writing code, can you help me?
is the code i changed right? how do i open the file to test it out with the new square?

**Comment by quasar098** [comment]
i cannot help you right now

i would recommend making these changes with a text editor locally and not on the github online editor ...

**Comment by quasar098** [comment]
what do you mean there are no py files after you unzip it?? what is going on there,

also, this is not a suitable change to midi-playground

**Pull request closed without merging**
