### PR TITLE
redme change

### PR DESCRIPTION
**Pull request by cangerjun**
Added Chinese README file
Added RedMe text switching function in other languages
Added a new suggestion for translators who join in the future.
In Chinese README the python version is recommended to be changed to 3.11.0

### CODE REVIEW

**Comment by quasar098** [comment]
i will look at this further soon

**Comment by quasar098** [comment]
it turns out it wasnt soon because i was busy and now i am even more busy with stuffs

**Comment by lucmsilva651** [comment]
I'll do a BR README for this project once this ZH one is approved. Let's see.

~ Lucas ;)

**Comment by quasar098** [comment]
ok i am still busy but i made time to approve this, also as you add translations for the readme you can just add more buttons by copy pasting for each document

**Pull request merged**
